# -*- coding: utf-8 -*-
"""Composing_Networks.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tXXu9S6bGYfhDfOf5mBR06CkIQ6frlO5

# Composing networks
"""

# Imports math library
import numpy as np
# Imports plotting library
import matplotlib.pyplot as plt

# Define the Rectified Linear Unit (ReLU) function
def ReLU(preactivation):
  activation = preactivation.clip(0.0)
  return activation

# Define a shallow neural network with, one input, one output, and three hidden units
def shallow_network(x, activation_fn, phi_0,phi_1,phi_2,phi_3, theta_10, theta_11, theta_20, theta_21, theta_30, theta_31):
  # Initial lines
  pre_1 = theta_10 + theta_11 * x
  pre_2 = theta_20 + theta_21 * x
  pre_3 = theta_30 + theta_31 * x
  # Activation functions
  act_1 = activation_fn(pre_1)
  act_2 = activation_fn(pre_2)
  act_3 = activation_fn(pre_3)
  # Weight activations
  w_act_1 = phi_1 * act_1
  w_act_2 = phi_2 * act_2
  w_act_3 = phi_3 * act_3
  # Combine weighted activation and add y offset
  y = phi_0 + w_act_1 + w_act_2 + w_act_3
  # Return y
  return y

# # Plot two shallow neural networks and the composition of the two
def plot_neural_two_components(x_in, net1_out, net2_out, net12_out=None):

  # Plot the two networks separately
  fig, ax = plt.subplots(1,2)
  fig.set_size_inches(8.5, 8.5)
  fig.tight_layout(pad=3.0)
  ax[0].plot(x_in, net1_out,'r-')
  ax[0].set_xlabel('Net 1 input'); ax[0].set_ylabel('Net 1 output')
  ax[0].set_xlim([-1,1]);ax[0].set_ylim([-1,1])
  ax[0].set_aspect(1.0)
  ax[1].plot(x_in, net2_out,'b-')
  ax[1].set_xlabel('Net 2 input'); ax[1].set_ylabel('Net 2 output')
  ax[1].set_xlim([-1,1]);ax[1].set_ylim([-1,1])
  ax[1].set_aspect(1.0)
  plt.show()

  if net12_out is not None:
    # Plot their composition
    fig, ax = plt.subplots()
    ax.plot(x_in ,net12_out,'g-')
    ax.set_xlabel('Net 1 Input'); ax.set_ylabel('Net 2 Output')
    ax.set_xlim([-1,1]);ax.set_ylim([-1,1])
    ax.set_aspect(1.0)
    plt.show()

x_values = np.linspace(-1, 1, 100)
x_values

n1_theta_10 = 0.0 ; n1_theta_11 = -1.0 ; n1_theta_20 = 0 ; n1_theta_21 = 1.0;
n1_theta_30 = -0.67 ; n1_theta_31 = 1.0 ; n1_phi_0 = 1.0; n1_phi_1 = -2.0; n1_phi_2 = -3.0;
n1_phi_3 = 9.3
n2_theta_10 = -0.6; n2_theta_11 = -1.0; n2_theta_20 = 0.2 ; n2_theta_21 = 1.0;
n2_theta_30 = -0.5 ; n2_theta_31 = 1.0; n2_phi_0 = 0.5; n2_phi_1 = -1.0; n2_phi_2 = -1.5;
n2_phi_3 = 2.0

y1 = shallow_network(x_values, ReLU, n1_phi_0,n1_phi_1,n1_phi_2,n1_phi_3, n1_theta_10, n1_theta_11, n1_theta_20, n1_theta_21, n1_theta_30, n1_theta_31)

y2 = shallow_network(x_values, ReLU, n2_phi_0,n2_phi_1,n2_phi_2,n2_phi_3, n2_theta_10, n2_theta_11, n2_theta_20, n2_theta_21, n2_theta_30, n2_theta_31)

plot_neural_two_components(x_values, y1, y2)

